### ISSUE TITLE
CalculateTrailingValues

### ISSUE THREAD

**Issue by mikkelsune** [TheCryptoBoss/Crypto-Boss-Feeder#1]
Could you please tell if I should set CalculateTrailingValues to "true" in the hostsettings.json? (hostsettings not included in your upload)

**Comment by scroll1** [comment]
that is what I set and it seems to work:
"CalculateTrailingValues": "true",
"UseMaxCostPercentage": "true",
"UseMinBuyBalancePercentage": "true",

**Comment by mikkelsune** [comment]
thanks
